sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t 2Bor2C/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true 2Bor2C/docker-react npm run test
